/*
Enter your query here.
*/
SELECT DEPARTMENTS.DEPT_NAME, COUNT(*)
FROM STUDENTS
    LEFT OUTER JOIN DEPARTMENTS 
        ON STUDENTS.DEPT_ID = DEPARTMENTS.DEPT_ID
GROUP BY STUDENTS.DEPT_ID
ORDER BY COUNT(*) DESC, DEPARTMENTS.DEPT_NAME ASC;